name: Check Flake
on:
  push:
    paths:
      - "**/*.nix"
      - "**/flake.lock"
  workflow_dispatch:

jobs:
  nix-flake-check:
    runs-on: native
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Run nix flake check
        run: nix flake check --no-update-lock-file --accept-flake-config --all-systems
