{ ... }:
{
  imports = [
    ./adguard.nix
    ./apolline.nix
    ./authelia.nix
    ./beszel/agent.nix
    ./beszel/hub.nix
    ./bitcoin.nix
    ./cloud-storage.nix
    ./cockpit.nix
    ./config_updater.nix
    ./container.nix
    ./ddclient.nix
    ./dev
    ./espanso.nix
    ./fail2ban.nix
    ./forgejo.nix
    ./gaming.nix
    ./gatus.nix
    ./git.nix
    ./headscale.nix
    ./home_automation
    ./homebank.nix
    ./homepage.nix
    ./incus.nix
    ./kde-connect.nix
    ./keepassxc
    ./konsole.nix
    ./librespeed.nix
    ./matrix
    ./multimedia.nix
    ./neovim.nix
    ./nextcloud.nix
    ./nginx
    ./nix-related.nix
    ./nixCache.nix
    ./office
    ./ollama.nix
    ./plasma
    ./portfolio.nix
    ./postgres.nix
    ./proxmox.nix
    ./restic.nix
    ./social
    ./sslh.nix
    ./thunderbird.nix
    ./tools.nix
    ./vaultwarden.nix
    ./vm.nix
    ./wakapi.nix
    ./watchtower.nix
    ./yubikey.nix
    ./zsh.nix
  ];
}
