{ ... }:
{
  imports = [
    ./cloud-storage
    ./dev
    ./office
    ./plasma
    ./social
    ./container.nix
    ./espanso.nix
    ./gaming.nix
    ./git.nix
    ./homebank.nix
    ./kde-connect.nix
    ./keepassxc
    ./konsole.nix
    ./multimedia.nix
    ./neovim.nix
    ./nix-related.nix
    ./thunderbird.nix
    ./tools.nix
    ./vm.nix
    ./zsh.nix
    ./ollama.nix
    ./postgres.nix
    # ./gitlab
    ./homepage.nix
    ./nextcloud.nix
    ./authelia.nix
    ./nginx
    ./beszel
    ./nixCache.nix
    ./adguard.nix
    ./fail2ban.nix
    ./ddclient.nix
    ./matrix
    ./home_automation
    ./watchtower.nix
    ./bitcoin.nix
    ./cockpit.nix
    ./librespeed.nix
    ./ghostty.nix
    ./apolline.nix
    ./forgejo.nix
    ./config_updater.nix
    ./gatus.nix
    ./restic.nix
    ./portfolio.nix
    ./incus.nix
    ./sslh.nix
    ./wakapi.nix
  ];
}
